# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

# AndroidX libraries are used instead of the legacy Support libraries.
android.useAndroidX=true

# Kotlin code style for the project.
kotlin.code.style=official

# Enables Gradle Configuration Cache for faster builds.
org.gradle.configuration-cache=true

# Specify JVM arguments for the Kotlin daemon.
kotlin.daemon.jvmargs=-Xmx2048m

# Path to the JDK used for Gradle.
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr
